### ISSUE TITLE
[Bug]: Emotecraft mod doesn't work well with Swem

### ISSUE THREAD

**Issue by monobanana1** [cavecomputing/SWEM-Beta#302] opened 2022-09-23 07:23 UTC
### What happened?

Having both mods installed causes the riding animations to not work correctly.

(I have a modpack that has over 300+ mods, maybe another mod is the problem, but I haven't checked).

### What should happen?

*

### Mods

emotecraft-for-MC1.16.5-2.2.5-forge

### SWEM Version

swem-1.16.5-0.5.1.0

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
*
```

**Comment by Mothfet** [comment] 2022-09-23 13:25
This is a conflict, not a bug. Both mods override the way player animations are handled when riding an entity. You would have to look in EmoteCraft's config to see if there's anything you can change - SWEM explicitly only applies player animations when riding a SWEM horse, so there's not really anything we can do about it on our end. Closing report.

**Closed** 2022-09-23 13:26 UTC
Labels: bug
