### ISSUE TITLE
[Bug]: Gait animations are broken on SWE server

### ISSUE THREAD

**Issue by justpeachysso** [cavecomputing/SWEM-Beta#137] opened 2021-11-23 01:03 UTC
### What happened?

On the SWE server, horses don't change animation above the walk. It just speeds up the walk. Tested on both single player and beta server, this bug only happens on SWE :)

### What should happen?

The horse should go up to the trot animation, canter, and so on 

### Mods

SWEM 1.16.5-0.1.6.10-b
Geckolib 3.0.35
Xaero's Minimap 21.15.5
Xaero's World Map 1.14.5
Optifine 1.0.0
Forge 36.1.0

### SWEM Version

0.1.6.10-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
N/A
```

**Comment by MagnusHJensen** [comment] 2021-12-06 13:59
Can't reproduce, maybe it was fixed in one of the newer versions! :D

**Closed by MagnusHJensen** 2021-12-06 13:59 UTC
Labels: bug
