### ISSUE TITLE
Cant put SWEM spawn egg into Shulker

### ISSUE THREAD

**Issue by drakexblud** [cavecomputing/SWEM-Beta#296] opened 2022-09-22 22:44 UTC
### What happened?

I clicked the SWEM spawn egg into my hotbar and tried putting in a shulker but it automatically disappears from my hotbar. 

And then I tried the same execution with my inventory. 

### What should happen?

Spawn egg should show up in the inventory/hot bar when trying to add it into a shulker box. 

### Mods

SWEM 1.16.5 

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment] 2022-09-24 13:20
Please attach a video where you reproduce, since I can't seem to do it.


https://user-images.githubusercontent.com/32039051/192100198-4c7d4ce2-26db-4bfd-85e5-013619c2aad3.mp4

**Comment by MagnusHJensen** [comment] 2022-09-24 15:30
Just figured out this is a cause from another thing.
Marking as duplicate see for updates. #271

**Closed by MagnusHJensen** 2022-09-24 15:30 UTC
Labels: duplicate
