### ISSUE TITLE
[Bug]: Can't place stall doors in ''Superflat/Overworld'' if there previously was a body of water/lava

### ISSUE THREAD

**Issue by NamiLovesSnakes** [cavecomputing/SWEM-Beta#295] opened 2022-09-22 15:41 UTC
### What happened?

It's pretty much in the title. Playing on the preset Superflat/Overworld and building a barn, I noticed that I can't place stall doors in places that had water or lava on them beforehand, even if I fill in all the space with dirt. Trees however don't seem to be an issue, if I cut them down I can place the stall doors there. Playing creative mode btw

### What should happen?

I think you should be able to place stall doors anywhere, given there's enough floorspace? At least I think that was the idea.

### Mods

Only the SWE-Mods 

### SWEM Version

release version

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment] 2022-09-22 19:50
Not sure what you mean.

Breaking a block, then placing a bucket of water in that hole, then filling it up with a block and the placing a door on it worked.

Mind sending a screenshot of your setup that does not work?

**Comment by NamiLovesSnakes** [comment] 2022-09-22 21:05
> Not sure what you mean.
> 
> Breaking a block, then placing a bucket of water in that hole, then filling it up with a block and the placing a door on it worked.
> 
> Mind sending a screenshot of your setup that does not work?

It's not about stuff I placed, it's about how the map generated. If the map generated water in an area, I cannot build stall doors on it. I can fill the entire body of water with dirt, but it will not let me place a stall door on floor level if there was water in that area generated by the game.

**Comment by MagnusHJensen** [comment] 2022-09-23 06:52
Can't reproduce closing.

If you send a video of an example where it happens, feel free to re-open.

**Closed by MagnusHJensen** 2022-09-23 06:52 UTC
Labels: bug
